version: '3.4'

services:
  finf1:
    image: finf1
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
